// Generated by CoffeeScript 1.10.0
(function() {
  var clean, handler, log, p;

  require('harmony-reflect');
  log = require('romgrk-logger');

  handler = {
    get: function(target, name) {
      log.warn('get', name);
      return target[name];
    },
    set: function(target, name, value) {
      log.warn('set', name);
      if (value !== target[name]) {
        target['%is-clean'] = false;
      }
      if (value === void 0) {
        delete target[name];
      } else {
        target[name] = value;
      }
      return value;
    }
  };

  clean = function(x) {
    x['%is-clean'] = true;
    return x;
  };

  p = Proxy({}, handler);

  p['a'] = 1;

  p['b'] = void 0;

  log.info(p['a'], p['b']);

  log.info("c" in p, p['c']);

  log.info(p);

  clean(p);

  p['a'] = 1;

  log.info(p);

  p['a'] = 42;

  log.info(p);

}).call(this);
