// Generated by CoffeeScript 1.10.0
(function() {
  var PORT, clients, history, log, logger, net, rd, readline, server, sk,
    slice = [].slice;

  net = require('net');

  readline = require('readline');

  logger = require('romgrk-logger');

  log = logger(console.log);

  log.method = function() {
    var args;
    args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    return process.stdout.write(args.join(' '));
  };

  PORT = 5000;

  sk = null;

  clients = [];

  history = [];

  rd = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
    completer: function(line) {
      return [history.slice(0, 1), line];
    }
  });

  server = net.createServer(function(socket) {
    sk = socket;
    clients += socket;
    log.a('Connected: ' + sk.remoteAddress + ': ' + sk.remotePort, '\n');
    socket.on('data', function(d) {
      log.text(log.erase.line + d.toString());
      return rd.prompt();
    });
    return socket.on('end', function() {
      sk = null;
      log.a('Disconnected\n');
      return rd.prompt();
    });
  });

  server.listen(PORT);

  log.a("Listening on port " + PORT + "...\n");

  rd.on('SIGINT', function() {
    return process.exit(0);
  });

  rd.on('line', function(line) {
    history.unshift(line);
    if (sk != null) {
      sk.write(line);
    } else {
      log.a('No socket\n');
    }
    return rd.prompt();
  });

  rd.on('close', function() {
    log.warn('Exiting.');
    return process.exit(0);
  });

}).call(this);
