// Generated by CoffeeScript 1.10.0
(function() {
  var BufferProxy, CurrentProxy, CursorProxy, DEFINE, Nvim, Path, Reflect, SYNCHRONIZE, TabpageProxy, VimProxy, WindowProxy, _, await, defer, fiber, hh, lib, ref, sync,
    slice = [].slice;

  _ = require('lodash');

  Path = require('path');

  Reflect = require('harmony-reflect');

  sync = require('synchronize');

  fiber = sync.fiber;

  await = sync.await;

  defer = sync.defer;

  hh = require('./helpers');

  module.exports = lib = {};

  DEFINE = function(properties) {
    return Object.defineProperties(lib, properties);
  };

  SYNCHRONIZE = function(object) {
    var apiFunc, func, k, ref, results, v;
    results = [];
    for (k in object) {
      v = object[k];
      apiFunc = ((ref = object[k]) != null ? ref.metadata : void 0) != null;
      if (!apiFunc) {
        continue;
      }
      func = object[k];
      sync(object, k);
      results.push(object[k].metadata = func.metadata);
    }
    return results;
  };

  Nvim = global.Nvim;

  SYNCHRONIZE(Nvim);

  SYNCHRONIZE(Nvim.Buffer.prototype);

  SYNCHRONIZE(Nvim.Window.prototype);

  SYNCHRONIZE(Nvim.Tabpage.prototype);

  Nvim = require('./nvim/nvim');

  BufferProxy = require('./nvim/buffer');

  TabpageProxy = require('./nvim/tabpage');

  WindowProxy = require('./nvim/window');

  ref = require('./nvim/proxies'), CurrentProxy = ref.CurrentProxy, VimProxy = ref.VimProxy, CursorProxy = ref.CursorProxy;

  lib.Nvim = lib.nvim = Nvim;

  DEFINE({
    current: {
      value: new CurrentProxy
    }
  });

  DEFINE({
    buffers: {
      get: function() {
        return _.filter(Nvim.getBuffers(), function(b) {
          return b.listed;
        });
      }
    },
    windows: {
      get: function() {
        return Nvim.getWindows();
      }
    },
    tabs: {
      get: function() {
        return Nvim.getTabpages();
      }
    }
  });

  DEFINE({
    cursor: {
      get: function() {
        return Nvim.getCurrentWindow().getCursor();
      },
      set: function(val) {
        var ref1, ref2;
        if (typeof val === 'number') {
          return Nvim.getCurrentWindow().setCursor([val, 0]);
        } else if (typeof val === 'object') {
          return Nvim.getCurrentWindow().setCursor([(ref1 = val.line) != null ? ref1 : cursor.line, (ref2 = val.row) != null ? ref2 : cursor.row]);
        } else {
          return Nvim.getCurrentWindow().setCursor([val[0], val[1]]);
        }
      }
    }
  });

  DEFINE({
    vim: {
      value: new VimProxy()
    }
  });

  DEFINE({
    call: {
      value: new Proxy({}, {
        get: function(t, fn) {
          return function() {
            var args;
            args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
            return Nvim.callFunction(fn, args != null ? args : []);
          };
        }
      })
    }
  });

  _.extend(lib, require('./nvim/functions'));

}).call(this);
