// Generated by CoffeeScript 1.10.0
(function() {
  var BufferProxy, CurrentProxy, CursorProxy, DEFINE, Functions, Highlight, Nvim, Path, Reflect, SYNCHRONIZE, TabpageProxy, VimProxy, Window, WindowProxy, _, await, defer, fiber, hh, lib, ref, ref1, sync;

  _ = require('lodash');

  Path = require('path');

  Reflect = require('harmony-reflect');

  sync = require('synchronize');

  fiber = sync.fiber;

  await = sync.await;

  defer = sync.defer;

  hh = require('./helpers');

  module.exports = lib = {};

  DEFINE = function(properties) {
    return Object.defineProperties(lib, properties);
  };

  SYNCHRONIZE = function(object) {
    var apiFunc, func, k, ref, results, v;
    results = [];
    for (k in object) {
      v = object[k];
      apiFunc = ((ref = object[k]) != null ? ref.metadata : void 0) != null;
      if (!apiFunc) {
        continue;
      }
      func = object[k];
      sync(object, k);
      results.push(object[k].metadata = func.metadata);
    }
    return results;
  };

  Nvim = global.Nvim;

  lib.Nvim = lib.nvim = Nvim;

  SYNCHRONIZE(Nvim);

  SYNCHRONIZE(Nvim.Buffer.prototype);

  SYNCHRONIZE(Nvim.Window.prototype);

  SYNCHRONIZE(Nvim.Tabpage.prototype);

  Nvim = require('./nvim/nvim');

  BufferProxy = require('./nvim/buffer');

  TabpageProxy = require('./nvim/tabpage');

  ref = require('./nvim/window'), WindowProxy = ref.WindowProxy, Window = ref.Window;

  ref1 = require('./nvim/proxies'), CurrentProxy = ref1.CurrentProxy, VimProxy = ref1.VimProxy, CursorProxy = ref1.CursorProxy;

  Functions = require('./nvim/functions');

  Highlight = require('./nvim/highlight').Highlight;

  lib.Window = Window;

  lib.Highlight = lib.hl = Highlight;

  _.extend(lib, Functions);

  DEFINE({
    current: {
      value: new CurrentProxy
    }
  });

  DEFINE({
    buffers: {
      get: function() {
        return _.filter(Nvim.getBuffers(), function(b) {
          return b.listed;
        });
      }
    }
  });

  DEFINE({
    windows: {
      get: function() {
        return Nvim.getWindows();
      }
    }
  });

  DEFINE({
    tabs: {
      get: function() {
        return Nvim.getTabpages();
      }
    }
  });

  DEFINE({
    cursor: {
      get: function() {
        return Nvim.getCurrentWindow().getCursor();
      },
      set: function(val) {
        var ref2, ref3;
        if (typeof val === 'number') {
          return Nvim.getCurrentWindow().setCursor([val, 0]);
        } else if (typeof val === 'object') {
          return Nvim.getCurrentWindow().setCursor([(ref2 = val.line) != null ? ref2 : cursor.line, (ref3 = val.row) != null ? ref3 : cursor.row]);
        } else {
          return Nvim.getCurrentWindow().setCursor([val[0], val[1]]);
        }
      }
    }
  });

  DEFINE({
    vim: {
      value: new VimProxy()
    }
  });

}).call(this);
