// Generated by CoffeeScript 1.10.0
(function() {
  var Path, Reflect, _, await, defer, fiber, hh, sync;

  _ = require('lodash');

  Path = require('path');

  Reflect = require('harmony-reflect');

  sync = require('synchronize');

  fiber = sync.fiber;

  await = sync.await;

  defer = sync.defer;

  module.exports = hh = {};

  hh.superClass = function(type) {
    return type.__super__ = _.extend({}, type.prototype);
  };

  global.RES = hh.res = function(object) {
    if (Buffer.isBuffer(object)) {
      return object.toString();
    }
    return object;
  };

  hh.addOptionDesc = function(obj, propName, optName) {
    var getFn, setFn;
    getFn = function() {
      return this.getOption(optName);
    };
    setFn = function(v) {
      return this.setOption(optName, v);
    };
    return obj.properties[propName] = {
      get: getFn,
      set: setFn
    };
  };

}).call(this);
