// Generated by CoffeeScript 1.10.0
(function() {
  var Path, Reflect, _, await, defer, fiber, lib, sync;

  _ = require('lodash');

  Path = require('path');

  Reflect = require('harmony-reflect');

  sync = require('../dev/sync');

  fiber = sync.fiber;

  await = sync.await;

  defer = sync.defer;

  module.exports = lib = {
    context: null,
    init: function(nvim) {
      var Nvim, context;
      Nvim = nvim;
      this.synchronize(Nvim);
      this.buffer = require('./buffer');
      this.buffer.init(Nvim.Buffer.prototype);
      this.synchronize(Nvim.Buffer.prototype);
      this.window = require('./window');
      this.window.init(Nvim.Window.prototype);
      this.synchronize(Nvim.Window.prototype);
      this.tabpage = require('./tabpage');
      this.tabpage.init(Nvim.Tabpage.prototype);
      this.synchronize(Nvim.Tabpage.prototype);
      context = require('./global')(Nvim);
      context.Nvim = Nvim;
      this.context = context;
      return context;
    },
    synchronize: function(object) {
      var apiFunc, func, k, ref, results, v;
      results = [];
      for (k in object) {
        v = object[k];
        apiFunc = ((ref = object[k]) != null ? ref.metadata : void 0) != null;
        if (!apiFunc) {
          continue;
        }
        func = object[k];
        sync(object, k);
        results.push(object[k].metadata = func.metadata);
      }
      return results;
    }
  };

}).call(this);
