// Generated by CoffeeScript 1.10.0
(function() {
  var BufferProxy, CursorProxy, Path, Reflect, TabpageProxy, VimProxy, WindowProxy, _, await, base, defer, define, fiber, lib, superClass, sync, synchronize;

  _ = require('lodash');

  Path = require('path');

  Reflect = require('harmony-reflect');

  sync = require('synchronize');

  fiber = sync.fiber;

  await = sync.await;

  defer = sync.defer;

  superClass = function(type) {
    return type.__super__ = _.extend({}, type.prototype);
  };

  define = function(obj, properties) {
    return Object.defineProperties(obj, properties);
  };

  synchronize = function(object) {
    var apiFunc, func, k, ref, results, v;
    results = [];
    for (k in object) {
      v = object[k];
      apiFunc = ((ref = object[k]) != null ? ref.metadata : void 0) != null;
      if (!apiFunc) {
        continue;
      }
      func = object[k];
      sync(object, k);
      results.push(object[k].metadata = func.metadata);
    }
    return results;
  };

  synchronize(Nvim);

  synchronize(Nvim.Buffer.prototype);

  synchronize(Nvim.Window.prototype);

  synchronize(Nvim.Tabpage.prototype);

  VimProxy = require('./nvim/vim');

  CursorProxy = require('./nvim/cursor');

  BufferProxy = require('./nvim/buffer');

  TabpageProxy = require('./nvim/tabpage');

  WindowProxy = require('./nvim/window');

  superClass(Nvim.Buffer);

  Nvim.Buffer.prototype.getProxy = function() {
    return this._proxy != null ? this._proxy : this._proxy = new BufferProxy(this);
  };

  superClass(Nvim.Tabpage);

  Nvim.Tabpage.prototype.getProxy = function() {
    return this._proxy != null ? this._proxy : this._proxy = new TabpageProxy(this);
  };

  superClass(Nvim.Window);

  Nvim.Window.prototype.getProxy = function() {
    return this._proxy != null ? this._proxy : this._proxy = new WindowProxy(this);
  };

  (base = Nvim.Window).prototype.getCursor = function() {
    return new CursorProxy(this, base.__super__.getCursor.call(this));
  };

  module.exports = lib = {};

  lib.Nvim = Nvim;

  lib.nvim = Nvim;

  define(lib, {
    buffer: {
      get: function() {
        return Nvim.getCurrentBuffer().getProxy();
      },
      set: function(b) {
        return Nvim.setCurrentBuffer(b);
      }
    },
    buffers: {
      get: function() {
        return _.map(Nvim.getBuffers(), function(b) {
          return b.getProxy();
        });
      }
    },
    window: {
      get: function() {
        return Nvim.getCurrentWindow().getProxy();
      },
      set: function(b) {
        return Nvim.setCurrentWindow(b);
      }
    },
    windows: {
      get: function() {
        return _.map(Nvim.getWindows(), function(b) {
          return b.getProxy();
        });
      }
    },
    tabpage: {
      get: function() {
        return Nvim.getCurrentTabpage().getProxy();
      },
      set: function(b) {
        return Nvim.setCurrentTabpage(b);
      }
    },
    tabpages: {
      get: function() {
        return _.map(Nvim.getTabpages(), function(b) {
          return b.getProxy();
        });
      }
    }
  });

  define(lib, {
    cursor: {
      get: function() {
        return Nvim.getCurrentWindow().getCursor();
      },
      set: function(val) {
        if (typeof val === 'number') {
          return Nvim.getCurrentWindow().setCursor([val, 0]);
        } else {
          return Nvim.getCurrentWindow().setCursor([val[0], val[1]]);
        }
      }
    }
  });

  define(lib, {
    vim: {
      value: new VimProxy()
    }
  });

  _.extend(lib, require('./nvim/functions'));

}).call(this);
