// Generated by CoffeeScript 1.10.0
(function() {
  var Reflect, Tabpage, TabpageProxy;

  Reflect = require('harmony-reflect');

  module.exports = Tabpage = {
    init: function(type) {
      var definition, key, ref;
      ref = this.properties;
      for (key in ref) {
        definition = ref[key];
        Object.defineProperty(type, key, definition);
      }
      return type.getProxy = function() {
        return new TabpageProxy(this);
      };
    }
  };

  Tabpage.properties = {
    window: {
      get: function() {
        return this.getWindow();
      }
    },
    windows: {
      get: function() {
        return this.getWindows();
      }
    },
    valid: {
      get: function() {
        return this.isValid();
      }
    }
  };

  TabpageProxy = (function() {
    function TabpageProxy(target) {
      return new Proxy(target, this);
    }

    TabpageProxy.prototype.get = function(target, name, receiver) {
      var varName;
      if (name.charAt(0) === ':') {
        varName = name.substring(1);
        return target.getVar(varName);
      }
      if (name in target) {
        return target[name];
      }
      return void 0;
    };

    TabpageProxy.prototype.set = function(target, name, val, receiver) {
      var varName;
      if (name.charAt(0) === ':') {
        varName = name.substring(1);
        target.setVar(varName, val);
      } else {
        target[name] = val;
      }
      return true;
    };

    return TabpageProxy;

  })();

}).call(this);
