// Generated by CoffeeScript 1.10.0
(function() {
  var AttributeProxy, Reflect, VBuffer, buf;

  Reflect = require('harmony-reflect');

  AttributeProxy = function(target) {
    return new Proxy(target, {
      get: function(target, name, receiver) {
        if (name in target) {
          return target[name];
        }
        if (name.charAt(0) === '&') {
          return 56;
        }
        return void 0;
      },
      set: function(target, name, val, receiver) {
        if (name.charAt(0) === '&') {
          target[name] = '&' + val.toString();
        } else {
          target[name] = val;
        }
        return true;
      }
    });
  };

  VBuffer = function() {
    this.name = 'fbads';
    this.number = 28;
    this['&type'] = 'file';
    return AttributeProxy(this);
  };

  VBuffer.prototype.size = function() {
    return log.info(10, 300);
  };

  buf = new VBuffer();

  log.info('name: ', buf.name);

  buf.size();

  log.info('&type: ', buf['&type']);

  log.info('number: ', buf['number']);

  buf['&ft'] = 'vim';

  log.info('&ft:', buf['&ft']);

}).call(this);
