// Generated by CoffeeScript 1.10.0
(function() {
  var BufferObject, BufferProxy, LineProxy, Reflect, _;

  _ = require('lodash');

  Reflect = require('harmony-reflect');

  LineProxy = (function() {
    LineProxy.prototype.buffer = null;

    function LineProxy(buffer1, target) {
      this.buffer = buffer1;
      return new Proxy(target, this);
    }

    LineProxy.prototype.get = function(target, name, receiver) {
      if (name === 'length') {
        return this.buffer.lineCount();
      }
      if (/^\d+$/.test(name)) {
        return this.buffer.getLine(~~name).toString();
      }
      if (name in target) {
        return target[name];
      }
      return void 0;
    };

    LineProxy.prototype.set = function(target, name, val, receiver) {
      if (/^\d+$/.test(name)) {
        this.buffer.setLine(~~name, val);
      }
      return true;
    };

    LineProxy.prototype.deleteProperty = function(target, name) {
      var e, error;
      if (/^\d+$/.test(name)) {
        try {
          this.buffer.delLine(~~name);
        } catch (error) {
          e = error;
          return false;
        }
        return true;
      }
      return Reflect.deleteProperty(target, name);
    };

    return LineProxy;

  })();

  BufferObject = {};

  BufferObject.properties = {
    length: {
      get: function() {
        return this.lineCount();
      }
    },
    number: {
      get: function() {
        return this.getNumber();
      }
    },
    name: {
      get: function() {
        return this.getName();
      },
      set: function(v) {
        return this.setName(v);
      }
    },
    valid: {
      get: function() {
        return this.isValid();
      }
    },
    listed: {
      get: function() {
        return this.getOption('buflisted');
      },
      set: function(v) {
        return this.setOption('buflisted', v);
      }
    },
    type: {
      get: function() {
        return this.getOption('buftype');
      },
      set: function(v) {
        return this.setOption('buftype', v);
      }
    }
  };

  BufferObject.methods = {
    "delete": function() {
      return Nvim.command('bdelete ' + this.number);
    },
    wipeout: function() {
      return Nvim.command('bwipeout ' + this.number);
    }
  };

  module.exports = BufferProxy = (function() {
    BufferProxy.LineProxy = LineProxy;

    function BufferProxy(buffer) {
      _.extend(buffer, BufferObject.methods);
      Object.defineProperties(buffer, BufferObject.properties);
      buffer.lines = new LineProxy(buffer, {});
      return new Proxy(buffer, this);
    }

    BufferProxy.prototype.get = function(target, name, receiver) {
      var optName, varName;
      switch (name.charAt(0)) {
        case ':':
          varName = name.substring(1);
          return target.getVar(varName);
        case '&':
          optName = name.substring(1);
          return target.getOption(optName);
      }
      if (/^\d+$/.test(name)) {
        return target.getLine(~~name).toString();
      }
      if (name in target) {
        return target[name];
      }
      return void 0;
    };

    BufferProxy.prototype.set = function(target, name, val, receiver) {
      var optName, varName;
      if (name.charAt(0) === ':') {
        varName = name.substring(1);
        target.setVar(varName, val);
      } else if (name.charAt(0) === '&') {
        optName = name.substring(1);
        target.setOption(optName, val);
      } else if (/^\d+$/.test(name)) {
        target.setLine(~~name, val);
      } else {
        target[name] = val;
      }
      return true;
    };

    BufferProxy.prototype.deleteProperty = function(target, name) {
      var e, error;
      if (/^\d+$/.test(name)) {
        try {
          target.delLine(~~name);
        } catch (error) {
          e = error;
          return false;
        }
        return true;
      }
      return Reflect.deleteProperty(target, name);
    };

    return BufferProxy;

  })();

}).call(this);
