// Generated by CoffeeScript 1.10.0
(function() {
  var CursorProxy, Reflect;

  Reflect = require('harmony-reflect');

  module.exports = CursorProxy = (function() {
    CursorProxy.prototype.window = null;

    function CursorProxy(window, cursor) {
      this.window = window;
      return new Proxy(cursor, this);
    }

    CursorProxy.prototype.get = function(target, name, receiver) {
      if (name === 'line') {
        return target[0];
      }
      if (name === 'row') {
        return target[1];
      }
      if (name in target) {
        return target[name];
      }
      return void 0;
    };

    CursorProxy.prototype.set = function(target, name, val, receiver) {
      if (name === 'line' || name === '0') {
        this.window.setCursor([val, target[1]]);
      } else if (name === 'row' || name === '1') {
        this.window.setCursor([target[0], val]);
      } else {
        target[name](val);
      }
      return true;
    };

    return CursorProxy;

  })();

}).call(this);
