// Generated by CoffeeScript 1.10.0
(function() {
  var Nvim, Reflect, _, hh;

  _ = require('lodash');

  hh = require('../helpers');

  Reflect = require('harmony-reflect');

  Nvim = global.Nvim;

  Nvim["super"] = _.extend({}, Nvim);

  Nvim.getCurrentBuffer = function() {
    return this["super"].getCurrentBuffer().getProxy();
  };

  Nvim.getCurrentWindow = function() {
    return this["super"].getCurrentWindow().getProxy();
  };

  Nvim.getCurrentTabpage = function() {
    return this["super"].getCurrentTabpage().getProxy();
  };

  Nvim.getBuffers = function() {
    return _.map(this["super"].getBuffers(), function(e) {
      return e.getProxy();
    });
  };

  Nvim.getWindows = function() {
    return _.map(this["super"].getWindows(), function(e) {
      return e.getProxy();
    });
  };

  Nvim.getTabpages = function() {
    return _.map(this["super"].getTabpages(), function(e) {
      return e.getProxy();
    });
  };

  module.exports = Nvim;

}).call(this);
