// Generated by CoffeeScript 1.10.0
(function() {
  var Nvim, Reflect, _, hh;

  _ = require('lodash');

  hh = require('../helpers');

  Reflect = require('harmony-reflect');

  Nvim = global.Nvim;

  Nvim.prototype = Object.getPrototypeOf(Nvim);

  hh.superClass(Nvim.prototype.constructor);

  Nvim.prototype.getCurrentBuffer = function() {
    return Nvim.__super__.getCurrentBuffer.call(this).getProxy();
  };

  Nvim.prototype.getCurrentWindow = function() {
    return Nvim.__super__.getCurrentWindow.call(this).getProxy();
  };

  Nvim.prototype.getCurrentTabpage = function() {
    return Nvim.__super__.getCurrentTabpage.call(this).getProxy();
  };

  Nvim.prototype.getBuffers = function() {
    return _.map(Nvim.__super__.getBuffers.call(this).getProxy());
  };

  Nvim.prototype.getWindows = function() {
    return _.map(Nvim.__super__.getWindows.call(this).getProxy());
  };

  Nvim.prototype.getTabpages = function() {
    return _.map(Nvim.__super__.getTabpages.call(this).getProxy());
  };

  module.exports = Nvim;

}).call(this);
