// Generated by CoffeeScript 1.10.0
(function() {
  var Reflect, Window, WindowProxy;

  Reflect = require('harmony-reflect');

  Window = {};

  Window.properties = {
    buffer: {
      get: function() {
        return this.getBuffer();
      }
    },
    width: {
      get: function() {
        return this.getWidth();
      },
      set: function(v) {
        return this.setWidth(v);
      }
    },
    height: {
      get: function() {
        return this.getHeight();
      },
      set: function(v) {
        return this.setHeight(v);
      }
    },
    cursor: {
      get: function() {
        return this.getCursor();
      },
      set: function(v) {
        return this.setCursor(v);
      }
    },
    position: {
      get: function() {
        return this.getPosition();
      }
    },
    tabpage: {
      get: function() {
        return this.getTabpage();
      }
    },
    valid: {
      get: function() {
        return this.isValid();
      }
    }
  };

  module.exports = WindowProxy = (function() {
    function WindowProxy(target) {
      Object.defineProperties(target, Window.properties);
      return new Proxy(target, this);
    }

    WindowProxy.prototype.get = function(target, name, receiver) {
      var optName, varName;
      switch (name.charAt(0)) {
        case ':':
          varName = name.substring(1);
          return target.getVar(varName);
        case '&':
          optName = name.substring(1);
          return target.getOption(optName);
      }
      if (/^\d+$/.test(name)) {
        return target.getLine(parseInt(name));
      }
      if (name in target) {
        return target[name];
      }
      return void 0;
    };

    WindowProxy.prototype.set = function(target, name, val, receiver) {
      var optName, varName;
      if (name.charAt(0) === ':') {
        varName = name.substring(1);
        target.setVar(varName, val);
      } else if (name.charAt(0) === '&') {
        optName = name.substring(1);
        target.setOption(optName, val);
      } else if (/^\d+$/.test(name)) {
        target.setLine(parseInt(name), val);
      } else {
        target[name] = val;
      }
      return true;
    };

    return WindowProxy;

  })();

}).call(this);
